# Generated by Django 5.1.15 on 2026-08-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='gateway_reference',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='upi_intent_url',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('FAILED', 'Failed')], default='PAID', max_length=20),
        ),
    ]
