# Generated by Django 5.1.15 on 2026-08-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_customersession_ended_at_customersession_started_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersession',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ORDERING', 'Ordering'), ('ORDER_PLACED', 'Order Placed'), ('FOOD_SERVED', 'Food Served'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
    ]
