# Generated by Django 5.1.15 on 2026-08-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_payment_flow_order_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Client submission key to prevent duplicate orders on retry/double-click', max_length=64),
        ),
    ]
