# Generated by Django 5.1.15 on 2026-09-01 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_image_url_menuitem_is_deleted'),
        ('orders', '0003_order_idempotency_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='menu.menuitem'),
        ),
    ]
